[package]
name = "ugs_metadata_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.4"
chrono = { version = "0.4.19", features = ["serde"] }
hyper = "0.14.18"
rusqlite = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
serde_repr = "0.1.8"
sqlx = { version = "0.5", features = ["chrono", "migrate", "runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }